title: Notes of Thi
description: You cannot remember everything.
baseurl: ""
url: "http://note.dinhanhthi.com"
repository: dinhanhthi/self-note

invisible: 1 # remove '#' if you want your site is invisible to search engine
paginate: 28

banner: "/assets/res/banner.png" # site banner (load when someone share your page url)
favicon: "/assets/res/favicon.png" # site's favicon (icon left side of your page)

# MatJek specific configurations
user: 
  name: "Dinh Anh Thi"
  email: "dinhanhthimail@gmail.com"
  website: "dinhanhthi.com"
  avatar: "/assets/res/user.png"
  github: "dinhanhthi"
google_tracking_id: ""
google_site_verification: ""
disqus_shortname: this-site

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true